export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_NEW_ARRIVALS_REQUEST = 'FETCH_NEW_ARRIVALS_REQUEST';
export const FETCH_NEW_ARRIVALS_SUCCESS = 'FETCH_NEW_ARRIVALS_SUCCESS';
export const FETCH_NEW_ARRIVALS_FAILURE = 'FETCH_NEW_ARRIVALS_FAILURE';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const SELECT_CART_ITEM_SIZE = 'SELECT_CART_ITEM_SIZE';
export const SELECT_CART_ITEM_COLOR = 'SELECT_CART_ITEM_COLOR';


